spring:
  datasource:
    url: jdbc:mariadb://localhost:3309/db?createDatabaseIfNotExist=true
    username: root
    password: root

camunda.bpm:
  webapp:
    index-redirect-enabled: true
#  admin-user:
#    id: test
#    password: test

  database:
    type: mariadb


app:
  ldap:
    serverUrl: ldap://localhost:9000/
    managerDn: cn=admin,dc=sandbox,dc=org
    managerPassword: admin
    baseDn: dc=sandbox,dc=org



